import {sectionFor,pocketsFor,type Arm,type Direction,type Pocket} from './model';
export type AllocationMode='auto'|'median'|'widen'|'reallocate'|'legacy-preserve';
export type FeatureAllocation={requested:number;medianUsed:number;reallocated:number;widening:number;start:number;end:number;mode:AllocationMode};
export const pocketFactor=(p:{length:number;taper:number},x:number,origin:number)=>{const t=Math.max(0,Math.min(1,(x-origin-p.length)/p.taper));return 1-t*t*(3-2*t);};
export const allocationMode=(a:Arm,p:Pocket):AllocationMode=>p.allocation??(a.corridorMode==='preserve'?'legacy-preserve':a.corridorMode==='widen'?'widen':'auto');
export const reserveWidth=(a:Arm,dir:Direction)=>sectionFor(a,dir).bands.filter(b=>b.type==='shoulder'||b.type==='buffer').reduce((s,b)=>s+b.width,0);
/** Single shared reserve, fairly apportioned between opposing requests. All consumers use this result. */
export function allocate(a:Arm,x=0,origin=0){const directions=['incoming','outgoing'] as const,result={} as Record<Direction,Record<'left'|'right',FeatureAllocation>>;let demand=0,legacyDemand=0,target=0;for(const dir of directions){result[dir]={} as Record<'left'|'right',FeatureAllocation>;for(const side of ['left','right'] as const){const p=pocketsFor(a,dir)[side],mode=allocationMode(a,p),requested=sectionFor(a,dir).width*p.lanes*pocketFactor(p,x,origin);result[dir][side]={requested,medianUsed:0,reallocated:0,widening:requested,start:origin,end:origin+p.length+p.taper,mode};if(side==='right'&&requested&&['auto','median','legacy-preserve'].includes(mode)){if(mode==='legacy-preserve')legacyDemand+=requested;else demand+=requested;target=Math.max(target,mode==='auto'?(a.residualTarget??1.5):.2);}}}
const available=Math.max(0,a.median-target-legacyDemand);for(const dir of directions){for(const side of ['left','right'] as const){const f=result[dir][side];if(side==='right'&&['auto','median','legacy-preserve'].includes(f.mode))f.medianUsed=f.mode==='legacy-preserve'?f.requested:Math.min(f.requested,available*f.requested/(demand||1));if(side==='left'&&['reallocate','legacy-preserve'].includes(f.mode))f.reallocated=Math.min(f.requested,reserveWidth(a,dir));f.widening=Math.max(0,f.requested-f.medianUsed-f.reallocated);}}
const medianUsed=directions.reduce((s,d)=>s+result[d].right.medianUsed,0),outward=directions.map(d=>result[d].left.widening+result[d].right.widening);return{features:result,medianUsed,residual:a.median-medianUsed,incomingMovement:outward[0],outgoingMovement:outward[1],widening:outward[0]+outward[1]};}
