import {sectionFor,pocketsFor,type Arm,type Direction} from './model';
export type Feedback={level:'geometry'|'engineering'|'note';message:string};
export const modeFor=(a:Arm)=>a.corridorMode??'widen'; // unmigrated legacy objects retain their appearance
export function pocketFactor(p:{length:number;taper:number},x:number,origin:number){const t=Math.max(0,Math.min(1,(x-origin-p.length)/p.taper));return 1-t*t*(3-2*t);}
export function pocketWidth(a:Arm,dir:Direction,which:'left'|'right',x=0,origin=0){const p=pocketsFor(a,dir)[which];return sectionFor(a,dir).width*p.lanes*pocketFactor(p,x,origin);}
export const reserveWidth=(a:Arm,dir:Direction)=>sectionFor(a,dir).bands.filter(b=>b.type==='shoulder'||b.type==='buffer').reduce((s,b)=>s+b.width,0);
/** Signed median edges can cross the alignment center; both directions share ONE reserve. */
export function medianEdges(a:Arm,x=0,origin=0){return modeFor(a)==='preserve'?[-a.median/2+pocketWidth(a,'outgoing','right',x,origin),a.median/2-pocketWidth(a,'incoming','right',x,origin)]:[-a.median/2,a.median/2];}
export function innerEdge(a:Arm,side:number,x=0,origin=0){return medianEdges(a,x,origin)[side===1?1:0];}
export function bandWidths(a:Arm,dir:Direction,x=0,origin=0){let used=modeFor(a)==='preserve'?pocketWidth(a,dir,'left',x,origin):0;return sectionFor(a,dir).bands.map(b=>{const take=b.type==='shoulder'||b.type==='buffer'?Math.min(used,b.width):0;used-=take;return b.width-take;});}
export function sectionImpact(a:Arm){const dirs=['incoming','outgoing'] as const;const right=dirs.reduce((s,d)=>s+pocketWidth(a,d,'right'),0),residual=a.median-(modeFor(a)==='preserve'?right:0),medianDeficit=right?Math.max(0,right+.2-a.median):0,curbDeficit=dirs.reduce((s,d)=>s+Math.max(0,pocketWidth(a,d,'left')-reserveWidth(a,d)),0),added=dirs.reduce((s,d)=>s+pocketWidth(a,d,'left')+pocketWidth(a,d,'right'),0),original=a.median+dirs.reduce((s,d)=>{const c=sectionFor(a,d);return s+a[d]*c.width+c.walk+c.bands.reduce((n,b)=>n+b.width,0);},0);return{original,result:original+(modeFor(a)==='widen'?added:0),added:modeFor(a)==='widen'?added:0,residual,medianDeficit,curbDeficit,required:medianDeficit+curbDeficit};}
export function corridorWarning(a:Arm):string|null{if(modeFor(a)!=='preserve')return null;const s=sectionImpact(a);if(s.medianDeficit>1e-6)return `Engineering Warning — พื้นที่เกาะกลางไม่พอสำหรับเลนเสริม ต้องการเพิ่ม ${s.medianDeficit.toFixed(2)} ม. (เว้นเนื้อเกาะ 0.20 ม. เพื่อวาดรูปเท่านั้น ไม่ใช่มาตรฐาน) เลือกอนุญาตขยายถนน ลดความกว้างเลน ปรับเกาะกลาง หรือยกเลิกเลนเสริม`;if(s.curbDeficit>1e-6)return `Engineering Warning — ไหล่ทาง/พื้นที่คั่นไม่พอสำหรับเลนริมทาง ต้องการเพิ่ม ${s.curbDeficit.toFixed(2)} ม. เลือกอนุญาตขยายถนน หรือปรับหน้าตัด`;return null;}
export function sectionFeedback(a:Arm):Feedback[]{const s=sectionImpact(a),warning=corridorWarning(a),out:Feedback[]=[];if(warning)out.push({level:'engineering',message:warning});if(s.added)out.push({level:'engineering',message:`ขยายแนวถนนและทางเท้า ${s.added.toFixed(2)} ม. ต้องตรวจสอบพื้นที่จริง`});if(modeFor(a)==='preserve'&&s.residual<a.median)out.push({level:'engineering',message:`เกาะกลางคงเหลือ ${s.residual.toFixed(2)} ม. ต้องทบทวนการใช้งานเกาะและพื้นที่พักคนข้าม`});out.push({level:'note',message:'ขนาดแนวถนนอ้างอิงเลนหลัก + เกาะกลาง + แถบหน้าตัด + ทางเท้า ช่วงโค้ง/Slip lane อาจต้องใช้พื้นที่เพิ่มเติม'});return out;}
