import {allocate,pocketFactor,reserveWidth} from './allocation';
import {sectionFor,pocketsFor,type Arm,type Direction} from './model';
export type Feedback={level:'geometry'|'engineering'|'note';message:string};
export const modeFor=(a:Arm)=>a.corridorMode??'widen'; // unmigrated legacy objects retain their appearance
export {pocketFactor,reserveWidth} from './allocation';
export function pocketWidth(a:Arm,dir:Direction,which:'left'|'right',x=0,origin=0){return allocate(a,x,origin).features[dir][which].requested;}
/** Signed median edges can cross the alignment center; both directions share ONE reserve. */
export function medianEdges(a:Arm,x=0,origin=0){const v=allocate(a,x,origin);return[-a.median/2+v.features.outgoing.right.medianUsed,a.median/2-v.features.incoming.right.medianUsed];}
export function innerEdge(a:Arm,side:number,x=0,origin=0){return medianEdges(a,x,origin)[side===1?1:0];}
export function bandWidths(a:Arm,dir:Direction,x=0,origin=0){let used=allocate(a,x,origin).features[dir].left.reallocated;return sectionFor(a,dir).bands.map(b=>{const take=b.type==='shoulder'||b.type==='buffer'?Math.min(used,b.width):0;used-=take;return b.width-take;});}
export function sectionImpact(a:Arm){const v=allocate(a),original=a.median+(['incoming','outgoing'] as const).reduce((s,d)=>{const c=sectionFor(a,d);return s+a[d]*c.width+c.walk+c.bands.reduce((n,b)=>n+b.width,0);},0),legacy=(['incoming','outgoing'] as const).filter(d=>v.features[d].right.mode==='legacy-preserve').reduce((s,d)=>s+v.features[d].right.requested,0),medianDeficit=legacy?Math.max(0,legacy+.2-a.median):0,curbDeficit=(['incoming','outgoing'] as const).reduce((s,d)=>s+(v.features[d].left.mode==='legacy-preserve'?v.features[d].left.widening:0),0);return{original,result:original+v.widening,added:v.widening,residual:v.residual,medianDeficit,curbDeficit,required:medianDeficit+curbDeficit};}
export function corridorWarning(a:Arm):string|null{const s=sectionImpact(a);if(s.medianDeficit>1e-6)return `Engineering Warning — พื้นที่เกาะกลางไม่พอสำหรับเลนเสริม ต้องการเพิ่ม ${s.medianDeficit.toFixed(2)} ม. (เว้นเนื้อเกาะ 0.20 ม. เพื่อวาดรูปเท่านั้น ไม่ใช่มาตรฐาน) เลือกอนุญาตขยายถนน ลดความกว้างเลน ปรับเกาะกลาง หรือยกเลิกเลนเสริม`;if(s.curbDeficit>1e-6)return `Engineering Warning — ไหล่ทาง/พื้นที่คั่นไม่พอสำหรับเลนริมทาง ต้องการเพิ่ม ${s.curbDeficit.toFixed(2)} ม. เลือกอนุญาตขยายถนน หรือปรับหน้าตัด`;return null;}
export function sectionFeedback(a:Arm):Feedback[]{const s=sectionImpact(a),warning=corridorWarning(a),out:Feedback[]=[];if(warning)out.push({level:'engineering',message:warning});if(s.added)out.push({level:'engineering',message:`ขยายแนวถนนและทางเท้า ${s.added.toFixed(2)} ม. ต้องตรวจสอบพื้นที่จริง`});if(s.residual<a.median)out.push({level:'engineering',message:`เกาะกลางคงเหลือ ${s.residual.toFixed(2)} ม. ต้องทบทวนการใช้งานเกาะและพื้นที่พักคนข้าม`});out.push({level:'note',message:'ขนาดแนวถนนอ้างอิงเลนหลัก + เกาะกลาง + แถบหน้าตัด + ทางเท้า ช่วงโค้ง/Slip lane อาจต้องใช้พื้นที่เพิ่มเติม'});return out;}
