import {roundSettings} from './roundabout';
import {roadObjects} from './objects';
import {type Design,sectionFor,pocketsFor,pocketLaneWidth} from './model';
import {activeIds,curbBoundsAt,armIslands,innerEdge,bandWidths,direction,laneY,approachSamples,bounds,carBounds,armTurn,armMouths,coreSize,edges,path,rotate,crossingIntervals,armTreatmentOrigins,dividerRange,slipArcState,slipAuxModeFor,slipAuxSeparatorAt,STOP_LINE_WIDTH} from './geometry';
import {resolvedArrowsForArm} from './arrow-layout';
import {pocketOriginFor,pocketFactorAt} from './allocation';
export function Mark({code,x,y,angle=0,mergeSide=1}:{code:string;x:number;y:number;angle?:number;mergeSide?:-1|1}){
if(code==='none')return null;
const merge=code==='merge',straight=['straight','sl','sr','all','su'].includes(code),left=['left','sl','lr','all'].includes(code),right=['right','sr','lr','all','ru'].includes(code),u=['uturn','su','ru'].includes(code);
return <g data-road-arrow="true" data-arrow-code={code} data-merge-side={merge?mergeSide:undefined} transform={`translate(${x} ${y}) rotate(${angle})`} fill="none" stroke="#fff" strokeWidth=".23" strokeLinejoin="round" strokeLinecap="round">
{merge?<><path d={`M-2.6 0H-.4Q.5 0 1.35 ${mergeSide*-.9}`}/><path d={`M.55 ${mergeSide*-.85}L1.35 ${mergeSide*-.9} 1.1 ${mergeSide*-.15}`}/></>:<>
<path d={straight?'M-2.6 0H2.3':right&&u?'M-2.6 0H.9':u?'M-2.6 0H-1':'M-2.6 0H-.6'}/>
{straight&&<path d="M1.5 -.55L2.3 0 1.5 .55"/>}
{left&&<path d="M-.6 0Q.25 0 .25 -.7V-1.3 M-.3 -.7L.25 -1.3 .8 -.7"/>}
{right&&(u?<path d="M.9 0Q1.65 0 1.65 .65V1.45 M1.1 .85L1.65 1.45 2.2 .85"/>:<path d="M-.6 0Q.25 0 .25 .7V1.3 M-.3 .7L.25 1.3 .8 .7"/>)}
{u&&<path d="M-1 0Q.35 .15 .35 .85Q.35 1.55 -1 1.55H-1.25 M-.65 1.05L-1.25 1.55 -.65 2.05"/>}
</>}
</g>}
export default function Drawing({d,selected,onSelect,onHandle}:{d:Design;selected:number;onSelect:(n:number)=>void;onHandle?:(e:React.PointerEvent<SVGCircleElement>,i:number)=>void}){const ids=activeIds(d),round=d.type==='roundabout',core=coreSize(d),segments=edges(d),mouths=armMouths(d),road='#35424e';const footprint=segments.flatMap(e=>e.outer.map(p=>rotate(p,armTurn(d,e.i))));const circleX=(y:number)=>Math.sqrt(Math.max(1,core*core-y*y));return <g className={d.showArrows?undefined:"hide-road-arrows"} transform={`rotate(${d.rotation})`}>
<style>{`.hide-road-arrows [data-road-arrow]{display:none}`}</style>
{/* One footprint owns the road, corner widening and slip-lane pavement. */}
<path d={path(footprint,true)} fill={road}/>
{segments.map(e=><g key={'boundary'+e.i} transform={`rotate(${d.arms[e.i].angle})`}><path d={path([...e.outer,...e.walk.slice().reverse()],true)} fill="#b9c5cc"/><path d={path(e.outer)} fill="none" stroke="#f6fafb" strokeWidth=".22"/>{e.island.length>0&&<path d={path(e.island,true)} fill="#b9c5cc" stroke="#f8f4d6" strokeWidth=".25" strokeLinejoin="round"/>}{e.slipApproachIsland.length>3&&<path data-slip-approach-island="true" d={path(e.slipApproachIsland,true)} fill="#b9c5cc" stroke="#f8f4d6" strokeWidth=".25" strokeLinejoin="round"/>}{e.slipReceivingIsland.length>3&&<path data-slip-receiving-island="true" d={path(e.slipReceivingIsland,true)} fill="#b9c5cc" stroke="#f8f4d6" strokeWidth=".25" strokeLinejoin="round"/>}{e.slipLead.length>1&&<path data-slip-lead-divider="true" d={path(e.slipLead)} fill="none" stroke="white" strokeWidth=".18" strokeDasharray="2 3"/>}{e.slipTrail.length>1&&<path data-slip-trail-divider="true" data-slip-trail-start={e.exitX} data-slip-full-end={e.slipFullEnd} data-slip-merge-end={e.slipMergeEnd} d={path(e.slipTrail)} fill="none" stroke="white" strokeWidth=".18" strokeDasharray="2 3"/>}{e.slip&&(()=>{const a=d.arms[e.i],s=slipArcState(e,a);return <>{a.slipCrossing&&<g data-slip-crossing="true">{Array.from({length:Math.max(1,Math.floor(a.slipWidth/.95))},(_,j)=>{const r0=s.inner+.15+j*.95,r1=Math.min(s.outer-.15,r0+.55);if(r1<=r0)return null;const ps=[...Array.from({length:9},(_,k)=>s.point(r0,s.crossT-s.crossHalf+2*s.crossHalf*k/8)),...Array.from({length:9},(_,k)=>s.point(r1,s.crossT+s.crossHalf-2*s.crossHalf*k/8))];return <path key={j} d={path(ps,true)} fill="white"/>;})}<path data-slip-stop="true" d={path([s.point(s.inner+.12,s.stopT),s.point(s.outer-.12,s.stopT)])} fill="none" stroke="white" strokeWidth=".48"/></g>}{e.arrow&&<Mark code="straight" x={s.arrowPoint.x} y={s.arrowPoint.y} angle={180-s.arrowT*180/Math.PI}/>}</>;})()}</g>)}
{ids.map(i=>{const core=mouths[i],a=d.arms[i],origins=armTreatmentOrigins(d,i,segments),stopX=origins.incoming,receiveX=origins.outgoing,walkIn=sectionFor(a,'incoming').walk,walkOut=sectionFor(a,'outgoing').walk,[lo,hi]=bounds(a,core,origins),carHi=carBounds(a,stopX,origins)[1],cross=crossingIntervals(a,core,round,roundSettings(d));const localAngle=(d.arms[i].angle+d.rotation)%360,medianExists=round||a.median>0;const crossBounds=round?curbBoundsAt(d,i,cross.x,segments):[lo,hi],crossBoundsEnd=round?curbBoundsAt(d,i,cross.x+3.2,segments):[lo,hi];const medianShape=armIslands(d,i,segments).map(ps=>path(ps,true)).join(' ');
return <g key={'arm'+i} transform={`rotate(${d.arms[i].angle})`} onPointerDown={e=>{e.stopPropagation();onSelect(i);}} style={{cursor:'pointer'}}><rect x={core+1} y={lo-walkOut} width={a.length-core-1} height={hi-lo+walkIn+walkOut} fill="transparent"/>{selected===i&&<rect data-selection="true" x={core+1} y={lo-walkOut-.7} width={a.length-core-1} height={hi-lo+walkIn+walkOut+1.4} fill="none" stroke="#0eabb8" strokeWidth=".45" strokeDasharray="2 1"/>}
{[-1,1].flatMap(side=>{let bandOffset=0;const section=sectionFor(a,direction(side));return section.bands.map((b,bi)=>{const inner=bandOffset;bandOffset+=b.width;const edge=side===1?segments.find(e=>e.i===i):segments.find(e=>e.next===i),limit=edge?.slip?(side===1?edge.cx:rotate({x:edge.cx-edge.radius*Math.sin(edge.sweep),y:edge.cy-edge.radius*Math.cos(edge.sweep)},-(Math.PI-edge.sweep)/(Math.PI/2)).x):0,start=Math.min(a.length,Math.max(stopX+3,core+8,limit+3)),xs=approachSamples(a,origins,start,a.length),edgeAt=(x:number,off:number)=>{const widths=bandWidths(a,direction(side),x,origins),before=widths.slice(0,bi).reduce((s,v)=>s+v,0),fraction=(off-inner)/b.width;return{x,y:carBounds(a,x,origins)[side===1?1:0]+side*(before+widths[bi]*fraction)}},ps=[...xs.map(x=>edgeAt(x,inner)),...xs.slice().reverse().map(x=>edgeAt(x,inner+b.width))];return <g key={side+b.id} data-band={b.type}><path d={path(ps,true)} fill={{bike:'#467d70',motorcycle:'#526c91',shoulder:'#66727c',buffer:'#899396'}[b.type]}/><path d={path(xs.map(x=>edgeAt(x,inner)))} fill="none" stroke="white" strokeWidth=".16"/>{b.type==='buffer'&&<path d={path(xs.map(x=>edgeAt(x,inner+b.width/2)))} stroke="white" strokeWidth=".2" strokeDasharray=".2 1" fill="none"/>}</g>;});})}
{medianExists?<path data-median-profile={round?'splitter-and-median':'median'} d={medianShape} fill={round?'#b3b9a7':'#7c9a80'} stroke="#f1d574" strokeWidth=".22"/>:<path d={`M${core+1} -.16H${a.length} M${core+1} .16H${a.length}`} stroke="#efd47a" strokeWidth=".16"/>}
{a.crossing&&<defs><mask id={`divider-mask-${i}`} maskUnits="userSpaceOnUse" x={0} y={Math.min(lo,crossBounds[0])-5} width={a.length+5} height={Math.max(hi,crossBounds[1])-Math.min(lo,crossBounds[0])+10}><rect x={0} y={Math.min(lo,crossBounds[0])-5} width={a.length+5} height={Math.max(hi,crossBounds[1])-Math.min(lo,crossBounds[0])+10} fill="white"/><rect x={cross.x-.2} y={lo-5} width="3.6" height={hi-lo+10} fill="black"/></mask></defs>}
{[1,-1].flatMap(side=>{const dir=direction(side),section=sectionFor(a,dir),pockets=pocketsFor(a,dir),rightWidth=pocketLaneWidth(a,dir,'right'),leftWidth=pocketLaneWidth(a,dir,'left'),rightOrigin=pocketOriginFor(origins,dir,'right'),channelized=slipAuxModeFor(d,i,dir,segments)==='channelized',n=a[dir],{mode,start,end}=dividerRange(a,core,round,side,roundSettings(d),origins.outgoing),lines:{key:string;first?:number;last:number;y:(x:number)=>number}[]=[];
for(let j=1;j<n;j++)lines.push({key:'main'+j,last:a.length,y:x=>innerEdge(a,side,x,origins)+side*(rightWidth*pockets.right.lanes*pocketFactorAt(pockets.right,x,origins,dir,'right')+section.width*j)});
for(const which of ['right','left'] as const){const p=pockets[which],w=which==='right'?rightWidth:leftWidth,pocketOrigin=pocketOriginFor(origins,dir,which);for(let j=0;j<p.lanes;j++)lines.push({key:which+j,first:pocketOrigin,last:pocketOrigin+p.length+p.taper,y:x=>innerEdge(a,side,x,origins)+side*(which==='right'?w*(j+1)*pocketFactorAt(p,x,origins,dir,which):rightWidth*pockets.right.lanes*pocketFactor(pockets.right,x,rightOrigin)+section.width*n+w*j*pocketFactorAt(p,x,origins,dir,which))});}
return lines.map(line=>{const lineStart=Math.max(start,line.first??start),solidEnd=mode==='solid'?Math.min(end,line.last):lineStart,dashStart=mode==='solid'?solidEnd:lineStart,ps=(from:number,to:number)=>path(approachSamples(a,origins,from,to).map(x=>({x,y:line.y(x)})));return <g key={side+line.key} data-lane-divider="true" data-divider-direction={dir} data-divider-mode={mode} strokeLinecap="butt" mask={a.crossing?`url(#divider-mask-${i})`:undefined} fill="none">{mode==='solid'&&solidEnd>lineStart&&<path data-divider-segment="solid" data-divider-start={lineStart} data-divider-end={solidEnd} d={ps(lineStart,solidEnd)} stroke="white" strokeWidth=".16"/>}{line.last>dashStart&&<path data-divider-segment="dashed" data-divider-start={dashStart} data-divider-end={line.last} d={ps(dashStart,line.last)} stroke="white" strokeWidth=".16" strokeDasharray="2 3"/>}</g>;});})}

{a.crossing&&<><defs><mask id={`zebra-${i}`} maskUnits="userSpaceOnUse" x={0} y={Math.min(lo,crossBounds[0])-5} width={a.length+5} height={Math.max(hi,crossBounds[1])-Math.min(lo,crossBounds[0])+10}><rect x={0} y={Math.min(lo,crossBounds[0])-5} width={a.length+5} height={Math.max(hi,crossBounds[1])-Math.min(lo,crossBounds[0])+10} fill="white"/>{medianExists&&<path data-median-profile={round?'splitter-and-median':'median'} d={medianShape} fill="black" stroke="black" strokeWidth=".35"/>}</mask></defs><g mask={`url(#zebra-${i})`}>{Array.from({length:Math.max(0,Math.floor((crossBounds[1]-crossBounds[0])/1.2))},(_,j)=>{const y=crossBounds[0]+j*1.2+.2,dy=crossBoundsEnd[0]-crossBounds[0];if(!round)return <rect key={j} x={cross.x} y={y} width="3.2" height=".65" fill="white"/>;return <path key={j} d={path([{x:cross.x,y},{x:cross.x+3.2,y:y+dy},{x:cross.x+3.2,y:y+dy+.65},{x:cross.x,y:y+.65}],true)} fill="white"/>;})}</g></>}
{a.stop&&a.incoming>0&&(round?<path d={`M${circleX(2)+roundSettings(d).yieldOffset} 2Q${circleX(hi/2)+roundSettings(d).yieldOffset} ${hi/2} ${circleX(hi-.2)+roundSettings(d).yieldOffset} ${hi-.2}`} stroke="white" strokeWidth=".45" strokeDasharray=".8 .6" fill="none"/>:<path d={`M${stopX} ${innerEdge(a,1,stopX,origins)+.2}V${carHi-.2}`} stroke="white" strokeWidth={STOP_LINE_WIDTH}/>)}
{(['incoming','outgoing'] as const).flatMap(dir=>{const ps=pocketsFor(a,dir);return (['left','right'] as const).flatMap(which=>Array.from({length:ps[which].lanes},(_,laneIndex)=><g key={`lane-id-${dir}-${which}-${laneIndex}`} data-pocket-lane={`${dir}-${which}`} data-pocket-index={laneIndex}/>));})}
{resolvedArrowsForArm(d,i,segments).map(v=><g key={`${v.direction}:${v.role}:${v.laneIndex}:${v.id}`} data-arrow-placement={v.id} data-arrow-manual={v.manual?'true':'false'}>{v.direction==='incoming'&&v.role==='main'?<g transform={`translate(${v.x} ${v.y}) rotate(${v.angle})`}><g transform="scale(1 .72)"><Mark code={v.code} x={0} y={0} mergeSide={v.mergeSide}/></g></g>:<Mark code={v.code} x={v.x} y={v.y} angle={v.angle} mergeSide={v.mergeSide}/>}</g>)}
{(a.medianOpenings??[]).filter(o=>(o.type??'opening')==='uturn').map(o=>{const x=Math.min(a.length-4,core+o.start+o.length+6),rp=pocketsFor(a,'incoming').right,f=pocketFactorAt(rp,x,origins,'incoming','right'),y=rp.lanes&&f>.35?innerEdge(a,1,x,origins)+pocketLaneWidth(a,'incoming','right')*.5*f:laneY(a,1,0,x,origins);return <g key={'uturn-'+o.id} data-uturn-opening={o.id}><Mark code="uturn" x={x} y={y} angle={180}/></g>;})}
{a.signal&&a.incoming>0&&<g data-traffic-signal="true" transform={`translate(${round?core+5:stopX} ${hi+1.7})`}><rect x="-2" y="-1" width="4" height="2" rx=".5" fill="#15232c"/>{['#f46b63','#e8bb48','#52bb91'].map((c,k)=><circle key={c} cx={-1.2+k*1.2} r=".4" fill={c}/>)}</g>}
{d.showNames&&<g data-road-name="true" transform={`translate(${a.length-14} ${hi+walkIn+6}) rotate(${-localAngle})`}><text textAnchor="middle" dominantBaseline="middle" fill="#294e60" fontFamily="Arial,Tahoma,sans-serif" fontSize="3" stroke="#edf2f4" strokeWidth="1.4" paintOrder="stroke">{a.name}</text></g>}{selected===i&&onHandle&&<g data-selection="true"><circle cx={a.length} cy={0} r="10" fill="transparent" onPointerDown={e=>onHandle(e,i)} style={{cursor:'move'}}/><circle cx={a.length} cy={0} r="2.6" fill="#087f8c" stroke="white" strokeWidth=".6" onPointerDown={e=>onHandle(e,i)} style={{cursor:'move'}}/><text x={a.length} y={-Math.max(-lo,hi)-7} transform={`rotate(${-localAngle} ${a.length} ${-Math.max(-lo,hi)-7})`} fontSize="2.8" textAnchor="middle" fill="#087f8c">{a.angle.toFixed(0)}° · {a.length.toFixed(0)} m</text></g>}</g>;})}
{roadObjects(d).map((o,i)=><g key={'object'+i} data-road-object="true" transform={`translate(${o.x} ${o.y}) rotate(${o.angle})`}>{o.kind==='tree'?<><circle r={o.size/2} fill="#609b73" stroke="#397a51" strokeWidth=".15"/><circle r=".18" fill="#8b6c4e"/></>:<><circle r=".28" fill="#556b7b"/><path d={`M0 0V${-o.side*o.reach}h.65`} fill="none" stroke="#637e8e" strokeWidth=".18"/></>}</g>)}
{round&&<><circle data-truck-apron="true" r={d.radius+roundSettings(d).apron} fill="#a9a293" stroke="#eee7d6" strokeWidth=".2"/><circle data-central-island="true" r={d.radius} fill="#86a58a" stroke="#f1d574" strokeWidth=".35"/>{Array.from({length:d.ring-1},(_,i)=><circle key={i} r={d.radius+roundSettings(d).apron+(i+1)*d.circulation/d.ring} stroke="#fff" strokeWidth=".16" strokeDasharray="2 3" fill="none"/>)}{[45,135,225,315].map(t=><g key={t} transform={`rotate(${t})`}><Mark code="straight" x={0} y={-(core-d.circulation/(2*d.ring))}/></g>)}</>}
</g>;}
