import {type Design,type Arm,type LaneRole,type LaneArrowCode,sectionFor,pocketsFor,roadsideFor,medianTreeDefaults,options,laneArrowFor,withLaneArrow,markingsFor} from './model';
import {autoLaneArrowPlacements,clampArrowOffset,laneArrowKey,manualPlacementsForLane,nextArrowId,normalizeArrowOverrides,resolvedArrow} from './arrow-layout';
import {allocate,allocationMode} from './allocation';
import {armMouth,edges,slipCrossLimit,slipArcState} from './geometry';
import {roundSettings} from './roundabout';
import {plantingPlan} from './planting';
import {type Selection,objectNames} from './selection';
import {Num,Pick,Toggle} from './controls';
export function QuickProperties({d,s,onArm,onDesign,onSelect}:{d:Design;s:Selection;onArm:(p:Partial<Arm>)=>void;onDesign:(d:Design)=>void;onSelect?:(s:Selection)=>void}){
const a=d.arms[s.arm],dir=s.direction??'incoming',section=sectionFor(a,dir),pockets=pocketsFor(a,dir),p=pockets[s.side??'right'],tree={...medianTreeDefaults(),...a.medianTrees},plant=plantingPlan(d,s.arm),round=d.type==='roundabout',r=roundSettings(d),slipEdge=edges(d).find(e=>e.i===s.arm),slipCrossMax=slipCrossLimit(slipEdge,a),slipReceiver=slipEdge?d.arms[slipEdge.next]:null,slipReceiverPockets=slipReceiver?pocketsFor(slipReceiver,'outgoing'):null,slipReceiving=slipReceiverPockets?.left??null;
const editSection=(patch:object)=>onArm({[dir==='incoming'?'incomingSection':'outgoingSection']:{...section,...patch}}),
editPocket=(patch:object)=>{
 const key=dir==='incoming'?'incomingPockets':'outgoingPockets',nextPockets={...pockets,[s.side??'right']:{...p,...patch}},next={...a,[key]:nextPockets};
 onArm({[key]:nextPockets,...('lanes' in patch?{laneMarkings:markingsFor(next),arrowOverrides:normalizeArrowOverrides(next)}:{})});
},
editMainCount=(count:number)=>{const next={...a,[dir]:count};onArm({[dir]:count,laneMarkings:markingsFor(next),arrowOverrides:normalizeArrowOverrides(next)});},
editTree=(patch:object)=>onArm({medianTrees:{...tree,...patch}});
const f=allocate(a).features[dir][s.side??'right'],laneIndex=s.laneIndex??0,laneRole:LaneRole=s.role??(s.kind==='pocket'?(s.side==='left'?'aux-left':'aux-right'):'main');
const laneArrow=laneArrowFor(a,dir,laneRole,laneIndex),arrowKey=laneArrowKey(dir,laneRole,laneIndex),arrowManual=!!a.arrowOverrides&&Object.prototype.hasOwnProperty.call(a.arrowOverrides,arrowKey);
const editArrow=(code:string)=>onArm({laneMarkings:withLaneArrow(a,dir,laneRole,laneIndex,code as LaneArrowCode)});
const edgeSet=edges(d),selectedArrow=s.kind==='arrow'&&s.id?resolvedArrow(d,s.arm,dir,laneRole,laneIndex,s.id,edgeSet):null;
const setManualArrows=(list:ReturnType<typeof manualPlacementsForLane>)=>onArm({arrowOverrides:{...(a.arrowOverrides??{}),[arrowKey]:list}});
const resetAutoArrows=()=>{const next={...(a.arrowOverrides??{})};delete next[arrowKey];onArm({arrowOverrides:Object.keys(next).length?next:undefined});};
const addArrow=()=>{const list=manualPlacementsForLane(d,s.arm,dir,laneRole,laneIndex,edgeSet),auto=autoLaneArrowPlacements(d,s.arm,dir,laneRole,laneIndex,edgeSet),id=nextArrowId(list),base=list.at(-1)?.offset??auto[0]?.offset??12,offset=clampArrowOffset(d,s.arm,dir,laneRole,laneIndex,base+(list.length?8:0),edgeSet),code:LaneArrowCode=laneArrow==='none'?'straight':laneArrow;setManualArrows([...list,{id,code,offset:+offset.toFixed(3)}]);onSelect?.({kind:'arrow',arm:s.arm,direction:dir,role:laneRole,laneIndex,id});};
const editSelectedArrow=(patch:{code?:LaneArrowCode;offset?:number})=>{if(!selectedArrow||!s.id)return;const list=manualPlacementsForLane(d,s.arm,dir,laneRole,laneIndex,edgeSet);setManualArrows(list.map(v=>v.id===s.id?{...v,...patch,...(patch.offset!==undefined?{offset:+clampArrowOffset(d,s.arm,dir,laneRole,laneIndex,patch.offset,edgeSet).toFixed(3)}:{})}:v));};
const deleteSelectedArrow=()=>{if(!s.id)return;const list=manualPlacementsForLane(d,s.arm,dir,laneRole,laneIndex,edgeSet).filter(v=>v.id!==s.id);setManualArrows(list);onSelect?.({kind:laneRole==='main'?'lane':'pocket',arm:s.arm,direction:dir,role:laneRole,laneIndex,...(laneRole==='aux-left'?{side:'left' as const}:laneRole==='aux-right'?{side:'right' as const}:{})});};
const duplicateSelectedArrow=()=>{if(!selectedArrow||!s.id)return;const list=manualPlacementsForLane(d,s.arm,dir,laneRole,laneIndex,edgeSet),source=list.find(v=>v.id===s.id);if(!source)return;const id=nextArrowId(list),offset=clampArrowOffset(d,s.arm,dir,laneRole,laneIndex,source.offset+8,edgeSet);setManualArrows([...list,{...source,id,offset:+offset.toFixed(3)}]);onSelect?.({kind:'arrow',arm:s.arm,direction:dir,role:laneRole,laneIndex,id});};
const editSlipReceiving=(patch:object)=>{if(!slipEdge||!slipReceiver||!slipReceiverPockets||!slipReceiving)return;const nextPockets={...slipReceiverPockets,left:{...slipReceiving,...patch}},next={...slipReceiver,outgoingPockets:nextPockets};onDesign({...d,arms:d.arms.map((v,i)=>i===slipEdge.next?{...next,laneMarkings:markingsFor(next),arrowOverrides:normalizeArrowOverrides(next)}:v)});};
const addSlipReceiving=()=>{if(!slipEdge||!slipReceiver||!slipReceiverPockets)return;const current=slipReceiverPockets.left,nextPockets={...slipReceiverPockets,left:{...current,lanes:Math.max(1,current.lanes),width:current.width??Math.max(2.5,Math.min(4.5,a.slipWidth)),allocation:'auto' as const}},next={...slipReceiver,outgoingPockets:nextPockets};onDesign({...d,arms:d.arms.map((v,i)=>i===slipEdge.next?{...next,laneMarkings:markingsFor(next),arrowOverrides:normalizeArrowOverrides(next)}:v)});onSelect?.({kind:'pocket',arm:slipEdge.next,direction:'outgoing',side:'left',role:'aux-left',laneIndex:0});};
const mouth=armMouth(d,s.arm),usableLength=Math.max(0,a.length-mouth);
const objectTitle=s.kind==='arrow'?'ลูกศรเลน':s.kind==='pocket'
 ?(dir==='incoming'
   ?`เลนรอเลี้ยว${s.side==='right'?'ขวา':'ซ้าย'}`
   :`เลนรับ · ${s.side==='right'?'ชิดเกาะกลาง':'ริมทาง'}`)
 :objectNames[s.kind];
return <div className="quick-properties"><h2>{objectTitle}{s.laneIndex!==undefined&&['lane','pocket'].includes(s.kind)?` · เลน ${s.laneIndex+1}`:''}</h2><p className="object-subtitle">{a.name}{s.direction?` · ${dir==='incoming'?'ขาเข้าแยก':'ขาออกแยก'}`:''}</p>
{['approach','lane'].includes(s.kind)&&<><Num label="จำนวนเลนหลัก" value={a[dir]} min={a[dir==='incoming'?'outgoing':'incoming']?0:1} max={4} onChange={editMainCount}/><Num label="ความกว้างเลน (ม.)" value={section.width} min={2.5} max={4.5} step={.25} onChange={width=>editSection({width})}/>{s.kind==='lane'&&<><Pick label={arrowManual?'รูปแบบ Auto (สำรอง)':'ลูกศร Auto'} value={laneArrow} items={options} onChange={editArrow}/><div className="arrow-actions"><button onClick={addArrow}>＋ เพิ่มลูกศร</button>{arrowManual&&<button onClick={resetAutoArrows}>กลับเป็น Auto</button>}</div><p className="j-small">{arrowManual?'เลนนี้ใช้ตำแหน่งลูกศรแบบกำหนดเอง':'ตำแหน่งลูกศรจัดอัตโนมัติ · ลากลูกศรบน Canvas เพื่อเปลี่ยนเป็น Manual'}</p></>} {s.kind==='approach'&&<><Num label="ความยาวจากปากแยกถึงปลายแบบ (ม.)" value={+usableLength.toFixed(1)} min={Math.max(12,45-mouth)} max={Math.max(12,400-mouth)} step={1} onChange={v=>onArm({length:mouth+v})}/><Num label="มุมขาถนน (°)" value={a.angle} min={0} max={359} onChange={angle=>onArm({angle})}/><p className="j-small">ความยาวที่แสดงวัดจากปากทางของขานี้ ไม่ใช่จากศูนย์กลางทางแยก</p></>}</>}
{s.kind==='sidewalk'&&<Num label="ความกว้างทางเท้า (ม.)" value={section.walk} min={0} max={5} step={.25} onChange={walk=>editSection({walk})}/>}
{s.kind==='band'&&(()=>{const b=section.bands.find(b=>b.id===s.id);return b?<><Pick label="ประเภทแถบ" value={b.type} items={{shoulder:'ไหล่ทาง',buffer:'พื้นที่คั่น',bike:'จักรยาน',motorcycle:'มอเตอร์ไซค์'}} onChange={type=>editSection({bands:section.bands.map(x=>x.id===b.id?{...x,type}:x)})}/><Num label="กว้างแถบ (ม.)" value={b.width} min={.25} max={4.5} step={.25} onChange={width=>editSection({bands:section.bands.map(x=>x.id===b.id?{...x,width}:x)})}/></>:null;})()}
{s.kind==='pocket'&&<><Num label="จำนวนเลนเสริม" value={p.lanes} min={0} max={3} onChange={lanes=>editPocket({lanes})}/><Num label={dir==='outgoing'?'ความกว้างเลนรับ (ม.)':'ความกว้างเลนเสริม (ม.)'} value={p.width??section.width} min={2.5} max={4.5} step={.25} onChange={width=>editPocket({width})}/><Pick label={arrowManual?'รูปแบบ Auto (สำรอง)':(dir==='outgoing'?'ลูกศรเลนรับ Auto':'ลูกศรเลนเสริม Auto')} value={laneArrow} items={options} onChange={editArrow}/><div className="arrow-actions"><button onClick={addArrow}>＋ เพิ่มลูกศร</button>{arrowManual&&<button onClick={resetAutoArrows}>กลับเป็น Auto</button>}</div><Num label={dir==='outgoing'?'ความยาวเลนรับ (ม.)':'ความยาวช่วงเต็ม (Storage) (ม.)'} value={p.length} min={5} max={140} onChange={length=>editPocket({length})}/><Num label={dir==='outgoing'?'ช่วงรวมเข้าช่องหลัก (Merge taper) (ม.)':'ช่วงสอบ (Taper) (ม.)'} value={p.taper} min={5} max={80} onChange={taper=>editPocket({taper})}/><div className="space-result"><b>ผลต่อหน้าตัด</b><p>ต้องการ {f.requested.toFixed(2)} ม.<br/>ใช้เกาะกลาง {f.medianUsed.toFixed(2)} ม.<br/>จัดสรรไหล่ทาง/คั่น {f.reallocated.toFixed(2)} ม.<br/>ขยายออก {f.widening.toFixed(2)} ม.<br/>เกาะคงเหลือ {allocate(a).residual.toFixed(2)} ม.</p></div><Pick label="การจัดสรรพื้นที่" value={allocationMode(a,p)} items={{auto:s.side==='right'?'Auto · ใช้เกาะกลางก่อน':'Auto · ขยายออก',...(s.side==='right'?{retain:'รักษาเกาะขั้นต่ำ / ขยายส่วนที่ขาด',widen:'คงเกาะกลาง / ขยายออก'}:{reallocate:'ใช้ไหล่ทาง/พื้นที่คั่น'}),...(allocationMode(a,p)==='median'?{median:'Legacy · ใช้เกาะกลางก่อน'}:{}),...(allocationMode(a,p)==='legacy-preserve'?{'legacy-preserve':'Legacy · คงรูปแบบไฟล์เดิม'}:{})}} onChange={allocation=>editPocket({allocation})}/>{allocationMode(a,p)==='retain'&&<Num label="เกาะกลางที่ต้องการคงไว้ (ม.)" value={p.retainedMedian??1.5} min={0} max={8} step={.1} onChange={retainedMedian=>editPocket({retainedMedian})}/>}<p className="j-small">Auto: เลนริมทางขยายออก; เลนชิดเกาะใช้พื้นที่เกาะก่อนและขยายเฉพาะส่วนที่ขาด ไม่มีค่าคงเหลือซ่อนอยู่</p></>}
{s.kind==='arrow'&&selectedArrow&&<><Pick label="ประเภทลูกศร" value={selectedArrow.code} items={Object.fromEntries(Object.entries(options).filter(([k])=>k!=='none'))} onChange={code=>editSelectedArrow({code:code as LaneArrowCode})}/><Num label="ระยะจากจุดอ้างอิงเลน (ม.)" value={+selectedArrow.offset.toFixed(1)} min={selectedArrow.minOffset} max={selectedArrow.maxOffset} step={.5} onChange={offset=>editSelectedArrow({offset})}/><div className="arrow-actions"><button onClick={duplicateSelectedArrow}>ทำสำเนา</button><button className="danger" onClick={deleteSelectedArrow}>ลบลูกศร</button></div><p className="j-small">ลากจุดจับบน Canvas เพื่อเลื่อนตามแนวเลน · การแก้ตำแหน่งจะเปลี่ยนเลนนี้จาก Auto เป็น Manual โดยคงลูกศรเดิมไว้</p></>}
{s.kind==='median'&&<><Num label="ความกว้างเกาะกลาง (ม.)" value={a.median} min={0} max={8} step={.5} onChange={median=>onArm({median})}/><Num label="ร่นหัวเกาะ (ม.)" value={a.medianOffset} min={0} max={35} onChange={medianOffset=>onArm({medianOffset})}/><p className="j-small">เกาะเหลือที่ปากทาง {allocate(a).residual.toFixed(2)} ม. รูปทรงเปลี่ยนตามช่วงสอบ</p></>}
{s.kind==='crossing'&&<><Toggle label="เปิดทางข้าม" checked={a.crossing} onChange={crossing=>onArm({crossing})}/><Num label="ร่นทางข้าม (ม.)" value={a.crossOffset} min={0} max={35} step={.5} onChange={crossOffset=>onArm({crossOffset})}/></>}
{['stop','yield'].includes(s.kind)&&<><Toggle label="แสดงเส้นหยุด / ให้ทาง" checked={a.stop} onChange={stop=>onArm({stop})}/>{round?<Num label="ระยะเส้นให้ทาง (ม.)" value={r.yieldOffset} min={.3} max={3} step={.1} onChange={yieldOffset=>onDesign({...d,roundabout:{...r,yieldOffset}})}/>:a.crossing?<p className="j-small">เส้นหยุดตามทางข้าม ปรับระยะที่ทางข้าม หรือปิดทางข้ามเพื่อกำหนดเส้นหยุดแยก</p>:<Num label="ร่นเส้นหยุด (ม.)" value={a.stopOffset} min={0} max={35} onChange={stopOffset=>onArm({stopOffset})}/>}</>}
{s.kind==='signal'&&<Toggle label="เปิดสัญญาณไฟ" checked={a.signal} onChange={signal=>onArm({signal})}/>}
{['slip','slipCrossing','slipArrow'].includes(s.kind)&&<><Toggle label="เปิด Slip lane" checked={a.slip} onChange={slip=>onArm({slip})}/><Num label="กว้าง Slip lane (ม.)" value={a.slipWidth} min={3} max={6} step={.25} onChange={slipWidth=>onArm({slipWidth})}/><Num label="รัศมีแนวกลาง Slip (ม.)" value={a.slipRadius} min={10} max={60} step={1} onChange={slipRadius=>onArm({slipRadius})}/>{slipEdge?.slip&&<div className="space-result"><b>ตำแหน่ง Slip lane</b><p>รัศมีที่ใช้จริง {slipEdge.radius.toFixed(1)} ม.<br/>จุดแยกจากปากแยก {(slipEdge.entryX-armMouth(d,s.arm)).toFixed(1)} ม.<br/>จุดบรรจบขาออก {(slipEdge.exitX-armMouth(d,slipEdge.next)).toFixed(1)} ม.</p></div>}<p className="j-small">Slip lane เพิ่มออกด้านนอกแนวถนนเดิม เพื่อคงเลนหลักเข้าแยกไว้ด้านใน รัศมีมากขึ้นทำให้จุดแยก/บรรจบถอยออกจากปากแยก; ระบบจะไม่ยอมรับค่าที่ไม่เหลือ channelizing island ที่สร้างได้</p><Toggle label="ทางข้ามบน Slip" checked={a.slipCrossing} onChange={slipCrossing=>onArm({slipCrossing})}/>{a.slipCrossing&&<><Num label="ตำแหน่งทางข้ามจากปลายโค้งขาออก (ม.)" value={Math.min(a.slipCrossOffset,slipCrossMax)} min={2} max={slipCrossMax} onChange={slipCrossOffset=>onArm({slipCrossOffset})}/><p className="j-small">คลิกทางม้าลายบนแผนแล้วลากจุดจับเพื่อย้ายตำแหน่งได้ · เส้นหยุด Slip จะขยับตามอัตโนมัติ</p></>}{slipEdge?.slip&&(()=>{const state=slipArcState(slipEdge,a);return <><Num label="ตำแหน่งลูกศรจากต้นโค้ง (ม.)" value={+(a.slipArrowOffset??state.centerLength/2).toFixed(1)} min={2} max={Math.max(2,state.centerLength-2)} onChange={slipArrowOffset=>onArm({slipArrowOffset})}/><p className="j-small">คลิกลูกศรบน Slip แล้วลากตามแนวโค้งได้</p></>;})()}<div className="j-subsection"><b>เลนรับหลัง Slip</b>{slipEdge&&slipReceiver&&slipReceiving?<>{slipReceiving.lanes? <><p className="j-small">{slipReceiver.name} · ขาออกริมทาง</p><Num label="จำนวนเลนรับ" value={slipReceiving.lanes} min={1} max={3} onChange={lanes=>editSlipReceiving({lanes})}/><Num label="ความกว้างเลนรับ (ม.)" value={slipReceiving.width??sectionFor(slipReceiver,'outgoing').width} min={2.5} max={4.5} step={.25} onChange={width=>editSlipReceiving({width})}/><Num label="Receiving length (ม.)" value={slipReceiving.length} min={5} max={140} onChange={length=>editSlipReceiving({length})}/><Num label="Merge taper (ม.)" value={slipReceiving.taper} min={5} max={80} onChange={taper=>editSlipReceiving({taper})}/><button onClick={()=>onSelect?.({kind:'pocket',arm:slipEdge.next,direction:'outgoing',side:'left',role:'aux-left',laneIndex:0})}>เลือกเลนรับบนแผน</button></>:<button onClick={addSlipReceiving}>＋ เพิ่มเลนรับหลัง Slip</button>}</>:<p className="j-small">ไม่พบขาทางออกที่รับการเลี้ยว</p>}</div></>}
{s.kind==='opening'&&(()=>{const o=a.medianOpenings?.find(o=>o.id===s.id);const patch=(p:object)=>onArm({medianOpenings:a.medianOpenings?.map(x=>x.id===s.id?{...x,...p}:x)});return o?<><Pick label="ประเภทช่องเปิด" value={o.type??'opening'} items={{opening:'ช่องเปิดเกาะกลางทั่วไป',uturn:'ช่องกลับรถ (U-turn)'}} onChange={type=>patch({type})}/><Num label="ระยะจากปากแยก (ม.)" value={o.start} min={0} max={a.length-armMouth(d,s.arm)-o.length-1} onChange={start=>patch({start})}/><Num label="ความยาวช่องเปิด (ม.)" value={o.length} min={2} max={40} onChange={length=>patch({length})}/>{(o.type??'opening')==='uturn'&&<p className="j-small">ช่องกลับรถเป็น treatment ระดับแนวคิด ต้องตรวจแนวกวาดรถ (design vehicle), sight distance และการจัดช่องรอเลี้ยวในขั้นออกแบบรายละเอียด</p>}</>:null;})()}
{s.kind==='central'&&<><Num label="รัศมีเกาะวงเวียน (ม.)" value={d.radius} min={10} max={30} onChange={radius=>onDesign({...d,radius})}/><Num label="ลานรถใหญ่ (ม.)" value={r.apron} min={0} max={4} step={.25} onChange={apron=>onDesign({...d,roundabout:{...r,apron}})}/><Num label="กว้างช่องจราจรวน (ม.)" value={d.circulation} min={3} max={22} step={.25} onChange={circulation=>onDesign({...d,circulation})}/></>}
{s.kind==='splitter'&&<><Num label="ความยาว Splitter (ม.)" value={r.splitterLength} min={12} max={40} onChange={splitterLength=>onDesign({...d,roundabout:{...r,splitterLength}})}/><Num label="ความกว้าง Splitter (ม.)" value={r.splitterWidth} min={1} max={6} step={.25} onChange={splitterWidth=>onDesign({...d,roundabout:{...r,splitterWidth}})}/><p className="j-small">ขนาด Splitter ใช้ร่วมทุกขาวงเวียน</p></>}
{s.kind==='landscape'&&<><Toggle label="ต้นไม้เกาะกลาง" checked={tree.enabled} onChange={enabled=>editTree({enabled})}/><Num label="ต้นแรกขั้นต่ำจากปากแยก (ม.)" value={tree.start} min={0} max={150} onChange={start=>editTree({start})}/><Num label="ระยะต้นไม้ (ม.)" value={tree.spacing} min={3} max={50} onChange={spacing=>editTree({spacing})}/><Num label="ความสูงต้นไม้เกาะ (ม.)" value={tree.height} min={2} max={15} step={.5} onChange={height=>editTree({height})}/><Num label="เส้นผ่านศูนย์กลางพุ่มเกาะ (ม.)" value={tree.crown} min={.5} max={8} step={.25} onChange={crown=>editTree({crown})}/><Num label="เยื้องศูนย์กลางเกาะ (ม.)" value={tree.offset} min={-3} max={3} step={.25} onChange={offset=>editTree({offset})}/><div className="space-result"><b>ตำแหน่งที่สร้างได้</b><p>ร้องขอ {tree.start.toFixed(1)} ม.<br/>ต้นแรกจริง {plant.actual===null?'ไม่มีพื้นที่':(plant.actual-plant.mouth).toFixed(1)+' ม.'}<br/>จำนวน {plant.trees.length} ต้น</p><p>{plant.reasons.join(' · ')}</p></div><p className="j-small">หาช่วงปลูกที่ใช้ได้ก่อนวางต้นไม้ ไม่ใช่การตรวจระยะมองเห็นหรือมาตรฐานภูมิทัศน์</p></>}
{['trees','lights'].includes(s.kind)&&(()=>{const rs=roadsideFor(d,a,dir),edit=(p:object)=>onArm({roadside:{incoming:roadsideFor(d,a,'incoming'),outgoing:roadsideFor(d,a,'outgoing'),[dir]:{...rs,...p}}});return <><Toggle label={s.kind==='trees'?'ต้นไม้ริมทาง':'เสาไฟริมทาง'} checked={s.kind==='trees'?rs.trees:rs.lights} onChange={v=>edit({[s.kind]:v})}/><Num label="ระยะห่างริมทาง (ม.)" value={rs.spacing} min={5} max={50} onChange={spacing=>edit({spacing})}/><Num label="ห่างขอบทาง (ม.)" value={rs.offset} min={0} max={5} step={.1} onChange={offset=>edit({offset})}/></>;})()}
</div>;}
