import {type Design,type Arm,type Direction,sectionFor,pocketsFor,roadsideFor,medianTreeDefaults} from './model';
import {allocate,allocationMode} from './allocation';
import {armMouth,stopPosition} from './geometry';
import {roundSettings} from './roundabout';
import {plantingPlan} from './planting';
import {type Selection,objectNames} from './selection';
import {Num,Pick,Toggle} from './controls';
export function QuickProperties({d,s,onArm,onDesign}:{d:Design;s:Selection;onArm:(p:Partial<Arm>)=>void;onDesign:(d:Design)=>void}){const a=d.arms[s.arm],dir=s.direction??'incoming',section=sectionFor(a,dir),pockets=pocketsFor(a,dir),p=pockets[s.side??'right'],tree={...medianTreeDefaults(),...a.medianTrees},plant=plantingPlan(d,s.arm),round=d.type==='roundabout',r=roundSettings(d);const editSection=(patch:object)=>onArm({[dir==='incoming'?'incomingSection':'outgoingSection']:{...section,...patch}}),editPocket=(patch:object)=>onArm({[dir==='incoming'?'incomingPockets':'outgoingPockets']:{...pockets,[s.side??'right']:{...p,...patch}}}),editTree=(patch:object)=>onArm({medianTrees:{...tree,...patch}});const f=allocate(a).features[dir][s.side??'right'];
return <div className="quick-properties"><h2>{objectNames[s.kind]}{s.kind==='pocket'?` · ${s.side==='left'?'ซ้าย':'ขวา'}`:''}</h2><p className="object-subtitle">{a.name}{s.direction?` · ${dir==='incoming'?'ขาเข้า':'ขาออก / เลนรับ'}`:''}</p>
{['approach','lane'].includes(s.kind)&&<><Num label="จำนวนเลนหลัก" value={a[dir]} min={a[dir==='incoming'?'outgoing':'incoming']?0:1} max={4} onChange={v=>onArm({[dir]:v})}/><Num label="ความกว้างเลน (ม.)" value={section.width} min={2.5} max={4.5} step={.25} onChange={width=>editSection({width})}/>{s.kind==='approach'&&<><Num label="ความยาวขาถนน (ม.)" value={a.length} min={60} max={180} onChange={length=>onArm({length})}/><Num label="มุมขาถนน (°)" value={a.angle} min={0} max={359} onChange={angle=>onArm({angle})}/></>}</>}
{s.kind==='sidewalk'&&<Num label="ความกว้างทางเท้า (ม.)" value={section.walk} min={0} max={5} step={.25} onChange={walk=>editSection({walk})}/>}
{s.kind==='band'&&(()=>{const b=section.bands.find(b=>b.id===s.id);return b?<><Pick label="ประเภทแถบ" value={b.type} items={{shoulder:'ไหล่ทาง',buffer:'พื้นที่คั่น',bike:'จักรยาน',motorcycle:'มอเตอร์ไซค์'}} onChange={type=>editSection({bands:section.bands.map(x=>x.id===b.id?{...x,type}:x)})}/><Num label="กว้างแถบ (ม.)" value={b.width} min={.25} max={4.5} step={.25} onChange={width=>editSection({bands:section.bands.map(x=>x.id===b.id?{...x,width}:x)})}/></>:null;})()}
{s.kind==='pocket'&&<><Num label="จำนวนเลนเสริม" value={p.lanes} min={0} max={3} onChange={lanes=>editPocket({lanes})}/><Num label="ความกว้างเลนทิศนี้ (ม.)" value={section.width} min={2.5} max={4.5} step={.25} onChange={width=>editSection({width})}/><Num label="Storage (ม.)" value={p.length} min={5} max={100} onChange={length=>editPocket({length})}/><Num label="Taper (ม.)" value={p.taper} min={5} max={60} onChange={taper=>editPocket({taper})}/><div className="space-result"><b>การใช้พื้นที่</b><p>ต้องการ {f.requested.toFixed(2)} ม.<br/>ใช้เกาะกลาง {f.medianUsed.toFixed(2)} ม.<br/>จัดสรรไหล่ทาง/คั่น {f.reallocated.toFixed(2)} ม.<br/>ขยายออก {f.widening.toFixed(2)} ม.<br/>เกาะคงเหลือ {allocate(a).residual.toFixed(2)} ม.</p></div><Pick label="การจัดสรรพื้นที่" value={allocationMode(a,p)} items={{auto:'Auto · คำนวณอัตโนมัติ',...(s.side==='right'?{median:'ใช้เกาะกลางให้มากก่อน'}:{reallocate:'จัดสรรไหล่ทาง/พื้นที่คั่น'}),widen:'คงเกาะกลาง / ขยายออก',...(allocationMode(a,p)==='legacy-preserve'?{'legacy-preserve':'คงรูปแบบไฟล์เดิม'}:{})}} onChange={allocation=>editPocket({allocation})}/><p className="j-small">เลนซ้าย Auto ขยายออก เลนขวาใช้เกาะก่อนและขยายส่วนที่ขาด</p><Num label="เกาะคงเหลือเป้าหมาย Auto (ม.)" value={a.residualTarget??1.5} min={.2} max={8} step={.1} onChange={residualTarget=>onArm({residualTarget})}/><p className="j-small">เป้าหมายแนวคิดที่ปรับได้ ไม่ใช่มาตรฐานขั้นต่ำ</p></>}
{s.kind==='median'&&<><Num label="ความกว้างเกาะกลาง (ม.)" value={a.median} min={0} max={8} step={.5} onChange={median=>onArm({median})}/><Num label="ร่นหัวเกาะ (ม.)" value={a.medianOffset} min={0} max={35} onChange={medianOffset=>onArm({medianOffset})}/><p className="j-small">เกาะเหลือที่ปากทาง {allocate(a).residual.toFixed(2)} ม. รูปทรงเปลี่ยนตามช่วงสอบ</p></>}
{s.kind==='crossing'&&<><Toggle label="เปิดทางข้าม" checked={a.crossing} onChange={crossing=>onArm({crossing})}/><Num label="ร่นทางข้าม (ม.)" value={a.crossOffset} min={0} max={35} step={.5} onChange={crossOffset=>onArm({crossOffset})}/></>}
{['stop','yield'].includes(s.kind)&&<><Toggle label="แสดงเส้นหยุด / ให้ทาง" checked={a.stop} onChange={stop=>onArm({stop})}/>{round?<Num label="ระยะเส้นให้ทาง (ม.)" value={r.yieldOffset} min={.3} max={3} step={.1} onChange={yieldOffset=>onDesign({...d,roundabout:{...r,yieldOffset}})}/>:a.crossing?<p className="j-small">เส้นหยุดตามทางข้าม ปรับระยะที่ทางข้าม หรือปิดทางข้ามเพื่อกำหนดเส้นหยุดแยก</p>:<Num label="ร่นเส้นหยุด (ม.)" value={a.stopOffset} min={0} max={35} onChange={stopOffset=>onArm({stopOffset})}/>}</>}
{s.kind==='signal'&&<Toggle label="เปิดสัญญาณไฟ" checked={a.signal} onChange={signal=>onArm({signal})}/>}
{s.kind==='slip'&&<><Toggle label="เปิด Slip lane" checked={a.slip} onChange={slip=>onArm({slip})}/><Num label="กว้าง Slip lane (ม.)" value={a.slipWidth} min={3} max={6} step={.25} onChange={slipWidth=>onArm({slipWidth})}/><Num label="รัศมี Slip lane (ม.)" value={a.slipRadius} min={20} max={50} onChange={slipRadius=>onArm({slipRadius})}/><Toggle label="ทางข้ามบน Slip" checked={a.slipCrossing} onChange={slipCrossing=>onArm({slipCrossing})}/><Num label="ตำแหน่งทางข้าม Slip (ม.)" value={a.slipCrossOffset} min={2} max={600} onChange={slipCrossOffset=>onArm({slipCrossOffset})}/></>}
{s.kind==='opening'&&(()=>{const o=a.medianOpenings?.find(o=>o.id===s.id);const patch=(p:object)=>onArm({medianOpenings:a.medianOpenings?.map(x=>x.id===s.id?{...x,...p}:x)});return o?<><Num label="ตำแหน่งช่องเปิด (ม.)" value={o.start} min={0} max={a.length-armMouth(d,s.arm)-o.length-1} onChange={start=>patch({start})}/><Num label="ความยาวช่องเปิด (ม.)" value={o.length} min={2} max={40} onChange={length=>patch({length})}/></>:null;})()}
{s.kind==='central'&&<><Num label="รัศมีเกาะวงเวียน (ม.)" value={d.radius} min={10} max={30} onChange={radius=>onDesign({...d,radius})}/><Num label="ลานรถใหญ่ (ม.)" value={r.apron} min={0} max={4} step={.25} onChange={apron=>onDesign({...d,roundabout:{...r,apron}})}/><Num label="กว้างช่องจราจรวน (ม.)" value={d.circulation} min={3} max={22} step={.25} onChange={circulation=>onDesign({...d,circulation})}/></>}
{s.kind==='splitter'&&<><Num label="ความยาว Splitter (ม.)" value={r.splitterLength} min={12} max={40} onChange={splitterLength=>onDesign({...d,roundabout:{...r,splitterLength}})}/><Num label="ความกว้าง Splitter (ม.)" value={r.splitterWidth} min={1} max={6} step={.25} onChange={splitterWidth=>onDesign({...d,roundabout:{...r,splitterWidth}})}/><p className="j-small">ขนาด Splitter ใช้ร่วมทุกขาวงเวียน</p></>}
{s.kind==='landscape'&&<><Toggle label="ต้นไม้เกาะกลาง" checked={tree.enabled} onChange={enabled=>editTree({enabled})}/><Num label="ต้นแรกขั้นต่ำจากปากแยก (ม.)" value={tree.start} min={0} max={150} onChange={start=>editTree({start})}/><Num label="ระยะต้นไม้ (ม.)" value={tree.spacing} min={3} max={50} onChange={spacing=>editTree({spacing})}/><Num label="ความสูงต้นไม้เกาะ (ม.)" value={tree.height} min={2} max={15} step={.5} onChange={height=>editTree({height})}/><Num label="เส้นผ่านศูนย์กลางพุ่มเกาะ (ม.)" value={tree.crown} min={.5} max={8} step={.25} onChange={crown=>editTree({crown})}/><Num label="เยื้องศูนย์กลางเกาะ (ม.)" value={tree.offset} min={-3} max={3} step={.25} onChange={offset=>editTree({offset})}/><div className="space-result"><b>ตำแหน่งที่สร้างได้</b><p>ร้องขอ {tree.start.toFixed(1)} ม.<br/>ต้นแรกจริง {plant.actual===null?'ไม่มีพื้นที่':(plant.actual-plant.mouth).toFixed(1)+' ม.'}<br/>จำนวน {plant.trees.length} ต้น</p><p>{plant.reasons.join(' · ')}</p></div><p className="j-small">หาช่วงปลูกที่ใช้ได้ก่อนวางต้นไม้ ไม่ใช่การตรวจระยะมองเห็นหรือมาตรฐานภูมิทัศน์</p></>}
{['trees','lights'].includes(s.kind)&&(()=>{const rs=roadsideFor(d,a,dir),edit=(p:object)=>onArm({roadside:{incoming:roadsideFor(d,a,'incoming'),outgoing:roadsideFor(d,a,'outgoing'),[dir]:{...rs,...p}}});return <><Toggle label={s.kind==='trees'?'ต้นไม้ริมทาง':'เสาไฟริมทาง'} checked={s.kind==='trees'?rs.trees:rs.lights} onChange={v=>edit({[s.kind]:v})}/><Num label="ระยะห่างริมทาง (ม.)" value={rs.spacing} min={5} max={50} onChange={spacing=>edit({spacing})}/><Num label="ห่างขอบทาง (ม.)" value={rs.offset} min={0} max={5} step={.1} onChange={offset=>edit({offset})}/></>;})()}
</div>;}
