import {type Design} from './model';
import {allocate} from './allocation';
import {activeIds,angleGap,armMouth,armTreatmentOrigins} from './geometry';
import {plantingPlan} from './planting';
import {roundFeedback,roundSettings} from './roundabout';
import type {Selection} from './selection';
export type Review={level:'geometry'|'engineering'|'note';message:string;selection:Selection};
const ANGLE_REVIEW=75,SEVERE_SKEW=60,MEDIAN_MIN=1.2,UTURN_GUIDE=6,NO_CHANGE=36,ROUND_CROSSING=7.5,REFUGE=1.8;
export function designReviews(d:Design):Review[]{const out:Review[]=[],ids=activeIds(d);
for(let k=0;k<ids.length;k++){const i=ids[k],next=ids[(k+1)%ids.length],gap=angleGap(d,i,next);if(gap<ANGLE_REVIEW)out.push({level:'engineering',selection:{kind:'approach',arm:i},message:`${d.arms[i].name} ↔ ${d.arms[next].name} · มุมระหว่างขาถนน ${gap.toFixed(0)}° ต่ำกว่า 75°${gap<=SEVERE_SKEW?' และอยู่ในช่วง severe skew':''} — งานใหม่ควรจัดแนวใกล้ 90°; สภาพเดิม/เขตทางจำกัดต้องทบทวน sight triangle และการควบคุมจราจร`});}
for(const i of ids){const a=d.arms[i],v=allocate(a);
for(const direction of ['incoming','outgoing'] as const)for(const side of ['left','right'] as const){const f=v.features[direction][side];if(f.widening>.001){const kind=direction==='incoming'?'เลนเสริม':'เลนเสริมขาออก',position=side==='right'?'ชิดเกาะกลาง':'ริมทาง';out.push({level:'note',selection:{kind:'pocket',arm:i,direction,side},message:`${a.name} · ${kind}${position}ทำให้ขอบทางขยายออก ${f.widening.toFixed(2)} ม. ตาม Auto allocation`});}}
if(a.median>0&&v.residual<MEDIAN_MIN-1e-6)out.push({level:'engineering',selection:{kind:'median',arm:i},message:`${a.name} · เกาะกลางคงเหลือ ${v.residual.toFixed(2)} ม. ต่ำกว่า 1.20 ม. ซึ่งเป็นค่าต่ำสุดอ้างอิงของเกาะกลางยกในแนวทางกรมทางหลวง — ใช้ Retain / Widen หรือทบทวนชนิดเกาะ`});
if(d.type!=='roundabout'&&a.crossing&&a.incoming>=2){const mode=a.dividerMode??'solid',length=a.solidLength??NO_CHANGE;if(mode!=='solid'||length<NO_CHANGE-1e-6)out.push({level:'engineering',selection:{kind:'lane',arm:i,direction:'incoming',role:'main',laneIndex:0},message:`${a.name} · ก่อนทางข้ามควรมีช่วงห้ามเปลี่ยนช่อง/เส้นทึบอย่างน้อย 36 ม. ตามคู่มือเครื่องหมายจราจรไทย; ค่าปัจจุบันคือ ${mode==='solid'?length.toFixed(0)+' ม.':'เส้นประตลอด'}`});}
if(d.type!=='roundabout'&&a.signal&&!a.stop)out.push({level:'engineering',selection:{kind:'signal',arm:i},message:`${a.name} · เปิดสัญญาณไฟแต่ปิดเส้นหยุด — แนวควบคุมสัญญาณต้องมีเส้นหยุด/ตำแหน่งหยุดที่สัมพันธ์กับทางข้ามและการมองเห็น`});
for(const o of a.medianOpenings??[])if((o.type??'opening')==='uturn'){out.push({level:'note',selection:{kind:'opening',arm:i,id:o.id},message:`${a.name} · ช่องกลับรถเป็นแนวคิดเบื้องต้น — ตรวจ design vehicle, แนวกวาดรถ, sight distance และการจัดช่องรอในขั้นรายละเอียด`});if(a.median<UTURN_GUIDE-1e-6)out.push({level:'engineering',selection:{kind:'opening',arm:i,id:o.id},message:`${a.name} · เกาะกลาง ${a.median.toFixed(2)} ม. แคบกว่าช่วง 6–10 ม. ที่แนวทางกรมทางหลวงใช้เป็นกรอบสำหรับ U-turn ที่สะดวก — ต้องตรวจ design vehicle และพื้นที่รับรถจริง`});}
const slip=d.slips.find(s=>s.fromArm===i);if(slip?.departure.mode==='acceleration'&&slip.crossing.enabled)out.push({level:'engineering',selection:{kind:'slip',arm:i},message:`${a.name} · ใช้ Slip acceleration lane ร่วมกับทางข้าม — ทบทวน conflict คนเดิน/จักรยานและ treatment ทางเลือกตามบริบทเมือง`});
const mouth=armMouth(d,i),origins=armTreatmentOrigins(d,i);for(const o of a.medianOpenings??[]){const os=mouth+o.start,oe=os+o.length;for(const direction of ['incoming','outgoing'] as const){const f=allocate(a,0,origins).features[direction].right;if(f.requested>0&&Math.max(os,f.start)<Math.min(oe,f.end))out.push({level:'engineering',selection:{kind:'opening',arm:i,id:o.id},message:`${a.name} · ช่องเปิดเกาะกลางทับช่วงเลนชิดเกาะของ${direction==='incoming'?'ขาเข้า':'ขาออก'} — ปรับตำแหน่งหรือ treatment ก่อนใช้งาน`});}}
const p=a.medianTrees?.enabled?plantingPlan(d,i):null;if(p){if(p.actual===null)out.push({level:'engineering',selection:{kind:'landscape',arm:i},message:`${a.name} · ไม่มีช่วงเกาะที่กว้างพอสำหรับพุ่ม / ระยะที่กำหนด`});else if(p.actual>p.requested+.1)out.push({level:'note',selection:{kind:'landscape',arm:i},message:`${a.name} · ต้นแรกถูกเลื่อนจากตำแหน่งที่ขอไปเป็น ${(p.actual-p.mouth).toFixed(1)} ม. — ${p.reasons.join(', ')}`});}
if(d.type==='roundabout'&&a.crossing&&a.incoming===1){const r=roundSettings(d),setback=a.crossOffset-r.yieldOffset;if(setback<ROUND_CROSSING-1e-6)out.push({level:'engineering',selection:{kind:'crossing',arm:i},message:`${a.name} · ทางข้ามวงเวียนอยู่ห่างแนวให้ทางประมาณ ${Math.max(0,setback).toFixed(1)} ม. ต่ำกว่าค่า review 7.5 ม. สำหรับ single-lane roundabout — ขยับทางข้ามออกและตรวจ queue/ทางเดินเท้า`});}}
if(d.type==='roundabout'){const r=roundSettings(d);if(ids.some(i=>d.arms[i].crossing)&&r.splitterWidth<REFUGE-1e-6)out.push({level:'engineering',selection:{kind:'central',arm:ids[0]},message:`Splitter island กว้าง ${r.splitterWidth.toFixed(1)} ม. ต่ำกว่า 1.8 ม. ที่ใช้เป็น minimum pedestrian refuge ใน guidance เสริม — เพิ่มความกว้างหรือออกแบบ refuge โดยเฉพาะ`});for(const message of roundFeedback(d))out.push({level:'engineering',selection:{kind:'central',arm:ids[0]},message});}return out;}
