import {roundSettings} from './roundabout';
import {sectionFor,pocketsFor,type Design,type Direction} from './model';
import {allocate} from './allocation';
import {armMouth,stopPosition,bandWidths,armIslands} from './geometry';
import {selectionKey,type Selection} from './selection';
export const sectionStart=(d:Design,id:number)=>d.type==='roundabout'?roundSettings(d).splitterLength+d.arms[id].medianOffset+8:0;
export function sectionPieces(d:Design,id:number,x:number){const a=d.arms[id],origin=stopPosition(a,armMouth(d,id)),allocation=allocate(a,x,origin),pieces:{width:number;label:string;kind:string;selection:Selection}[]=[];const add=(width:number,label:string,kind:string,selection:Selection)=>{if(width>.001)pieces.push({width,label,kind,selection});};
for(const direction of ['outgoing','incoming'] as const){const section=sectionFor(a,direction),f=allocation.features[direction],bands=bandWidths(a,direction,x,origin),sidePieces:typeof pieces=[];const prev=pieces.length;
add(f.right.requested,'เสริมขวา','aux',{kind:'pocket',arm:id,direction,side:'right'});for(let j=0;j<a[direction];j++)add(section.width,direction==='incoming'?'←':'→','lane',{kind:'lane',arm:id,direction});add(f.left.requested,'เสริมซ้าย','aux',{kind:'pocket',arm:id,direction,side:'left'});section.bands.forEach((b,k)=>add(bands[k],{bike:'จักรยาน',motorcycle:'มอเตอร์ไซค์',shoulder:'ไหล่ทาง',buffer:'คั่น'}[b.type],b.type,{kind:'band',arm:id,direction,id:b.id}));add(section.walk,'ทางเท้า','walk',{kind:'sidewalk',arm:id,direction});if(direction==='outgoing'){const sub=pieces.splice(prev).reverse();pieces.push(...sub);const planted=armIslands(d,id).some(poly=>Math.min(...poly.map(p=>p.x))<=x&&Math.max(...poly.map(p=>p.x))>=x);const opening=a.medianOpenings?.find(o=>x>=armMouth(d,id)+o.start&&x<=armMouth(d,id)+o.start+o.length);add(allocation.residual,opening?'ช่องเปิด':planted?'เกาะกลาง':'พื้นที่กลาง',opening||!planted?'lane':'median',opening?{kind:'opening',arm:id,id:opening.id}:{kind:'median',arm:id});}}
return{pieces,allocation};}
export function CrossSection({d,id,x,onX,selection,onSelect}:{d:Design;id:number;x:number;onX:(x:number)=>void;selection:Selection;onSelect:(s:Selection)=>void}){const a=d.arms[id],mouth=armMouth(d,id),{pieces,allocation}=sectionPieces(d,id,x);return <section className="precision-section" aria-label="หน้าตัดถนนแบบโต้ตอบ"><header><b>หน้าตัด · {a.name}</b><label>จากปากแยก <input aria-label="ตำแหน่งหน้าตัด" type="range" min={sectionStart(d,id)} max={Math.max(sectionStart(d,id)+1,a.length-mouth)} value={x-mouth} onChange={e=>onX(mouth+Number(e.target.value))}/><span>{(x-mouth).toFixed(1)} ม.</span></label></header><div className="section-components">{pieces.map((p,i)=><button key={i} className={`section-piece ${p.kind} ${selectionKey(selection)===selectionKey(p.selection)?'active':''}`} style={{flex:p.width}} title={`${p.label} ${p.width.toFixed(2)} ม.`} aria-label={`หน้าตัด ${p.label} ${p.selection.direction??''}`} onClick={()=>onSelect(p.selection)}><span>{p.label}</span><small>{p.width.toFixed(2)}</small></button>)}</div><footer><span>{d.type==='roundabout'?'หน้าตัดแนวตรงหลัง Splitter · มิติเป็นเมตร':'มิติเป็นเมตร · คลิกส่วนที่ต้องการแก้ไข'}</span>{a.medianTrees?.enabled&&<button onClick={()=>onSelect({kind:'landscape',arm:id})}>♧ ต้นไม้เกาะกลาง</button>}<span>เกาะเหลือ {allocation.residual.toFixed(2)} · ขยาย {allocation.widening.toFixed(2)}</span></footer></section>;}
