export type Point={x:number;y:number};
export type RoadConfig={lanes:number;laneWidth:number;median:number;shoulder:number;traffic:'Left'|'Right'};
export type Road={id:string;name:string;a:Point;b:Point;config:RoadConfig};
export type Component={id:string;roadId:string;kind:'Junction'|'Turn Pocket'|'Median Opening';t:number;side:number;width:number;taper:number;storage:number;length:number};
export const presets:Record<string,RoadConfig>={'2-Lane Undivided':{lanes:1,laneWidth:3.25,median:0,shoulder:1,traffic:'Left'},'4-Lane Divided':{lanes:2,laneWidth:3.25,median:4,shoulder:1.5,traffic:'Left'},'6-Lane Divided':{lanes:3,laneWidth:3.5,median:5,shoulder:1.5,traffic:'Left'}};
export const SCALE=5;
export function generateRoad(road:Road){const c=road.config;const length=Math.hypot(road.b.x-road.a.x,road.b.y-road.a.y);const angle=Math.atan2(road.b.y-road.a.y,road.b.x-road.a.x)*180/Math.PI;const median=c.median*SCALE,lane=c.laneWidth*SCALE,shoulder=c.shoulder*SCALE,half=median/2+c.lanes*lane+shoulder;return{length,angle,median,lane,shoulder,half,transform:`translate(${road.a.x} ${road.a.y}) rotate(${angle})`,dividers:Array.from({length:c.lanes-1},(_,i)=>median/2+(i+1)*lane),arrows:[-1,1].flatMap(side=>Array.from({length:c.lanes},(_,i)=>({y:side*(median/2+(i+.5)*lane),forward:c.traffic==='Left'?side===-1:side===1}))) };}
export function project(p:Point,r:Road){const dx=r.b.x-r.a.x,dy=r.b.y-r.a.y,l2=dx*dx+dy*dy;const t=Math.max(.05,Math.min(.95,((p.x-r.a.x)*dx+(p.y-r.a.y)*dy)/l2));const x=r.a.x+t*dx,y=r.a.y+t*dy;return{t,distance:Math.hypot(p.x-x,p.y-y),side:((p.x-x)*-dy+(p.y-y)*dx)>=0?1:-1};}
export function demo():{roads:Road[];components:Component[]}{return{roads:[{id:'r1',name:'Main corridor',a:{x:100,y:300},b:{x:1080,y:300},config:{...presets['4-Lane Divided'],median:5}}],components:[{id:'c1',roadId:'r1',kind:'Junction',t:.66,side:1,width:3.25,taper:12,storage:20,length:40},{id:'c2',roadId:'r1',kind:'Turn Pocket',t:.645,side:1,width:3.25,taper:14,storage:22,length:12},{id:'c3',roadId:'r1',kind:'Median Opening',t:.22,side:1,width:3.25,taper:12,storage:20,length:10}]};}
