// Run verify-junction.cjs first to compile TS modules.
const assert=require('node:assert/strict'),fs=require('fs'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),sharp=require('../node_modules/.pnpm/sharp@0.34.5/node_modules/sharp');
const {initial,migrate,sectionFor,emptyPockets}=require('../.sites-runtime/model.cjs'),g=require('../.sites-runtime/geometry.cjs'),sm=require('../.sites-runtime/slip-model.cjs'),Drawing=require('../.sites-runtime/drawing.cjs').default;
const design=initial();design.arms.forEach(a=>{a.length=160;a.corridorMode="widen";});const a=design.arms[0];a.incomingSection={width:3.5,walk:3,bands:[{id:'bike',type:'bike',width:1.5}]};a.outgoingSection={width:3,walk:1.5,bands:[{id:'shoulder',type:'shoulder',width:1}]};a.incomingPockets={left:{lanes:1,length:30,taper:20},right:{lanes:2,length:25,taper:20}};a.outgoingPockets={left:{lanes:2,length:35,taper:25},right:{lanes:1,length:25,taper:15}};
const edgeSet=g.edges(design),origins=g.armTreatmentOrigins(design,0,edgeSet),origin=origins.incoming;assert.equal(origins.outgoing,edgeSet.find(e=>e.next===0).exitX);assert.equal(g.carBounds(a)[1],18.5);assert.equal(g.carBounds(a)[0],-16);assert.equal(g.carBounds(a,160,origins)[1],8);assert.equal(g.carBounds(a,160,origins)[0],-7);assert.equal(g.bounds(a,160,origins)[1],9.5);assert.equal(g.bounds(a,160,origins)[0],-8);
assert.equal(g.designError(design),null);assert.deepEqual(migrate(JSON.parse(JSON.stringify(design))),design);assert.equal(g.pocketFactor(a.incomingPockets.left,origin+30,origin),1);assert.equal(g.pocketFactor(a.incomingPockets.left,origin+50,origin),0);assert.equal(g.pocketFactor(a.incomingPockets.left,origin+40,origin),.5);
assert.equal(g.laneY(a,1,0,origin,origins),9.75);assert.equal(g.laneY(a,1,0,160,origins),2.75);
assert.equal(sectionFor(design.arms[1],'incoming').width,3.25);assert.equal(sectionFor(a,'outgoing').bands[0].type,'shoulder');
const tooShort=structuredClone(design);tooShort.arms[0].length=60;assert(g.designError(tooShort));
const samples=[['pockets',design]];for(const angle of [15,315]){const d=structuredClone(design);d.arms[0].angle=angle;samples.push(['pockets-angle'+angle,d]);}let slip=sm.addSlip(structuredClone(design),0);slip.arms[0].incomingPockets.left.length=80;slip.arms[0].incomingPockets.right.length=80;samples.push(['pockets-slip-overlay',slip]);const round=structuredClone(design);round.type='roundabout';round.radius=30;round.circulation=18;round.arms.forEach(a=>a.signal=false);samples.push(['pockets-round',round]);
(async()=>{for(const [name,d] of samples){assert.equal(g.designError(d),null,name);const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="-190 -190 380 380" width="1200" height="1200">'+renderToStaticMarkup(React.createElement(Drawing,{d,selected:-1,onSelect:()=>{}}))+'</svg>';assert.equal((svg.match(/data-pocket-lane=/g)||[]).length,6,name+' pocket lane identity count');assert(!/NaN|Infinity/.test(svg));fs.writeFileSync('.sites-runtime/'+name+'.svg',svg);await sharp(Buffer.from(svg)).png().toFile('.sites-runtime/'+name+'.png');}const receiving=initial();receiving.arms.forEach((arm,i)=>{arm.length=180;arm.angle=[13,101,194,287][i];arm.crossing=false;arm.outgoingPockets=emptyPockets();arm.outgoingPockets.right={lanes:1,width:3.1,length:40,taper:25,allocation:'auto'};arm.laneMarkings=undefined;});const receivingSvg=renderToStaticMarkup(React.createElement(Drawing,{d:receiving,selected:-1,onSelect:()=>{}}));assert.equal((receivingSvg.match(/data-arrow-code="merge"/g)||[]).length,4,'one merge arrow per arm');assert.equal((receivingSvg.match(/data-merge-side="1"/g)||[]).length,4,'median-side receiving arrows merge toward main lane in local coordinates');assert(!receivingSvg.includes('data-arrow-suppressed="true"'));
fs.writeFileSync('.sites-runtime/pockets-demo.json',JSON.stringify(design));console.log('PASS independent cross sections, incoming left/right pockets, outgoing receiving lanes, editable merge arrows, lengths/tapers, skew/slip/round geometries, SVG and JSON');})();
